//@version=5
indicator(title='MACD', shorttitle='MACD')

// Getting inputs
fast_length = input(title='Fast Length', defval=12)
slow_length = input(title='Slow Length', defval=26)
src = input(title='Source', defval=close)
signal_length = input.int(title='Signal Smoothing', minval=1, maxval=50, defval=9)
sma_source = input(title='Simple MA(Oscillator)', defval=false)
sma_signal = input(title='Simple MA(Signal Line)', defval=false)

// Plot colors
col_grow_above = #26A69A
col_grow_below = #FFCDD2
col_fall_above = #B2DFDB
col_fall_below = #EF5350
col_macd = #0094ff
col_signal = #ff6a00

// Calculating
sma_1 = ta.sma(src, fast_length)
ema_1 = ta.ema(src, fast_length)
fast_ma = sma_source ? sma_1 : ema_1
sma_2 = ta.sma(src, slow_length)
ema_2 = ta.ema(src, slow_length)
slow_ma = sma_source ? sma_2 : ema_2
macd = fast_ma - slow_ma
sma_3 = ta.sma(macd, signal_length)
ema_3 = ta.ema(macd, signal_length)
signal = sma_signal ? sma_3 : ema_3
hist = macd - signal

plot(hist, title='Histogram', style=plot.style_columns, color=hist >= 0 ? hist[1] < hist ? col_grow_above : col_fall_above : hist[1] < hist ? col_grow_below : col_fall_below)
plot(macd, title='MACD', color=color.new(col_macd, 0))
plot(signal, title='Signal', color=color.new(col_signal, 0))
