//@version=5
indicator(title='Moving Averages 5 & 20 & 200', shorttitle='MA5&20&200', overlay=true)

mv5_len = input.int(5, minval=1, title='Length')
mv5_src = input(close, title='Source')
mv5_out = ta.sma(mv5_src, mv5_len)

mv20_len = input.int(20, minval=1, title='Length')
mv20_src = input(close, title='Source')
mv20_out = ta.sma(mv20_src, mv20_len)

mv200_len = input.int(200, minval=1, title='Length')
mv200_src = input(close, title='Source')
mv200_out = ta.sma(mv200_src, mv200_len)

plot(mv200_out, color=color.new(#0b6ce5, 0), title='MA200')
plot(mv5_out, color=color.white, title='MA5')
plot(mv20_out, color=color.new(#00d5ff, 0), title='MA20')